name: Build and Push Nix Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  summer-body-bot:
    name: Build & Push summer-body-bot
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build summer-body-bot Docker image
        run: nix build .#summer-body-bot-docker

      - name: Load image into Docker
        run: docker load < result

      - name: Tag image
        run: docker tag summer-body-bot ghcr.io/tietokilta/summer-body-bot:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/tietokilta/summer-body-bot:latest

  wappupokemonbot:
    name: Build & Push wappupokemonbot
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build wappupokemonbot Docker image
        run: nix build .#wappupokemonbot-docker

      - name: Load image into Docker
        run: docker load < result

      - name: Tag image
        run: docker tag wappupokemonbot ghcr.io/tietokilta/wappupokemonbot:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/tietokilta/wappupokemonbot:latest

  tikbot:
    name: Build & Push tikbot
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build tikbot Docker image
        run: nix build .#tikbot-docker

      - name: Load image into Docker
        run: docker load < result

      - name: Tag image
        run: docker tag tikbot ghcr.io/tietokilta/tikbot:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/tietokilta/tikbot:latest
